USE [master]
GO

/****** Object:  Database [TransactionDb]    Script Date: 28/5/2018 08:09:44 ******/
CREATE DATABASE [TransactionDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TransactionDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TransactionDb.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TransactionDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\TransactionDb_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TransactionDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TransactionDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TransactionDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TransactionDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TransactionDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TransactionDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [TransactionDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TransactionDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TransactionDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TransactionDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TransactionDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TransactionDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TransactionDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TransactionDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TransactionDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TransactionDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TransactionDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TransactionDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TransactionDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TransactionDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TransactionDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TransactionDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [TransactionDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TransactionDb] SET RECOVERY FULL 
GO

ALTER DATABASE [TransactionDb] SET  MULTI_USER 
GO

ALTER DATABASE [TransactionDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TransactionDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TransactionDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TransactionDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TransactionDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TransactionDb] SET QUERY_STORE = OFF
GO

USE [TransactionDb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TransactionDb] SET  READ_WRITE 
GO


